{
 "title": "Kubernetes Nodes Status",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "zone",
    "query": "FOO-B,BAR-B,BAZ-A,BAZ-B,FOON-A,FOON-B"
   },
   { "name": "ds", "query": "prometheus" },
   {
    "name": "node",
    "query": "label_values(kube_node_info,node)"
   },
   {
    "name": "kernel_version",
    "query": "label_values(kube_node_info,kernel_version)"
   },
   {
    "name": "docker_version",
    "query": "label_values(kube_node_info,container_runtime_version)"
   },
   {
    "name": "kubelet_version",
    "query": "label_values(kube_node_info,kubelet_version)"
   }
  ]
 },
 "panels": [
  {
   "title": "NotReady",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"unknown\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Unschedulable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Kubelet Version Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_info{node=~\"$node\"}) by (kubelet_version)",
     "legendFormat": "{{kubelet_version}}"
    }
   ]
  },
  {
   "title": "Docker Version Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_info{node=~\"$node\"}) by (container_runtime_version)",
     "legendFormat": "{{container_runtime_version}}"
    }
   ]
  },
  {
   "title": "Docker Version Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_info{node=~\"$node\"}) by (kernel_version)",
     "legendFormat": "{{kernel_version}}"
    }
   ]
  },
  {
   "title": "Nums Of Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_info{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "K8S Node Status",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "(kube_node_status_condition{condition=\"Ready\",status=\"unknown\",node=~\"$node\"}) * on(node) group_right() (sum(kube_node_labels) by (label_cloud_foo_com_role,node)*on(node) group_right(label_cloud_foo_com_role) sum(kube_node_info{container_runtime_version=~\"$docker_version\",kernel_version=~\"$kernel_version\",kubelet_version=~\"$kubelet_version\"}) by (container_runtime_version,kernel_version,kubelet_version,node))"
    }
   ]
  },
  { "title": "overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } }
 ]
}